// Monitoring and Observability Generators
// Generated by Xaheen CLI

export type { TelemetryAnalyticsOptions } from "./telemetry-analytics.generator";
export { TelemetryAnalyticsGenerator } from "./telemetry-analytics.generator";

// Monitoring Generator Factory
export class MonitoringGeneratorFactory {
	static createTelemetryAnalyticsGenerator() {
		return new TelemetryAnalyticsGenerator();
	}

	static getSupportedTypes() {
		return ["telemetry-analytics"] as const;
	}

	static createGenerator(type: string) {
		switch (type) {
			case "telemetry-analytics":
				return this.createTelemetryAnalyticsGenerator();
			default:
				throw new Error(`Unsupported monitoring type: ${type}`);
		}
	}
}

export type MonitoringType = ReturnType<
	typeof MonitoringGeneratorFactory.getSupportedTypes
>[number];
